plugins {
    id 'java'
    id 'application'
}

application {
    mainClass = 'Main'
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
}

jar {
    archiveFileName = 'fq_download.jar'
    manifest {
        attributes 'Main-Class': 'Main'
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
